# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
rules:
- apiGroups:
    - extensions.gardener.cloud
  resources:
    - clusters
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - containerruntimes
  - containerruntimes/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - secrets/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - extension-runtime-kata-leader-election
  verbs:
  - get
  - watch
  - update
  - patch
- apiGroups:
    - resources.gardener.cloud
  resources:
    - managedresources
  verbs:
    - get
    - list
    - create
    - delete
    - watch
    - patch
    - update
- apiGroups:
    - ""
    - apps
    - batch
    - rbac.authorization.k8s.io
    - admissionregistration.k8s.io
    - apiextensions.k8s.io
  resources:
    - namespaces
    - events
    - secrets
    - configmaps
    - endpoints
    - deployments
    - services
    - serviceaccounts
    - clusterroles
    - clusterrolebindings
    - roles
    - rolebindings
    - jobs
    - pods
    - pods/log
    - mutatingwebhookconfigurations
    - customresourcedefinitions
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name" . }} 
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
