# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: kata-deploy 
description: This helmchart bundles kata-deploy and modifications for firecracker 

# This is the chart version.
version: 0.0.1 
