# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the Gardener Runtime Katacontainers extension 
name: gardener-extension-runtime-kata
version: 0.1.0
